CREATE TABLE `AEROLINEA` (
	`ID_AEROLINEA` int NOT NULL AUTO_INCREMENT,
	`NOMBRE_AEROLINEA` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID_AEROLINEA`)
);

INSERT INTO AEROLINEA (NOMBRE_AEROLINEA) VALUES ('Volaris');
INSERT INTO AEROLINEA (NOMBRE_AEROLINEA) VALUES ('Aeromar');
INSERT INTO AEROLINEA (NOMBRE_AEROLINEA) VALUES ('Interjet');
INSERT INTO AEROLINEA (NOMBRE_AEROLINEA) VALUES ('Aeromexico');

CREATE TABLE `AEROPUERTO` (
	`ID_AEROPUERTO` int NOT NULL AUTO_INCREMENT,
	`NOMBRE_AEROPUERTO` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID_AEROPUERTO`)
);

INSERT INTO AEROPUERTO (NOMBRE_AEROPUERTO) VALUES ('Benito Juarez');
INSERT INTO AEROPUERTO (NOMBRE_AEROPUERTO) VALUES ('Guanajuato');
INSERT INTO AEROPUERTO (NOMBRE_AEROPUERTO) VALUES ('La paz');
INSERT INTO AEROPUERTO (NOMBRE_AEROPUERTO) VALUES ('Oaxaca');

CREATE TABLE `MOVIMIENTOS` (
	`ID_MOVIMIENTO` int NOT NULL AUTO_INCREMENT,
	`DESCRIPCION` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`ID_MOVIMIENTO`)
);

INSERT INTO MOVIMIENTOS (DESCRIPCION) VALUES ('Salida');
INSERT INTO MOVIMIENTOS (DESCRIPCION) VALUES ('Llegada');

CREATE TABLE `VUELOS` (
	`ID_AEROLINEA` int NOT NULL,
	`ID_AEROPUERTO` varchar(255) NOT NULL,
    `ID_MOVIMIENTO` varchar(255) NOT NULL,
    `DIA` DATE NOT NULL
);

create table `VUELOS` (
	`ID_AEROLINEA` int NOT NULL,
	`ID_AEROPUERTO` int NOT NULL,
    `ID_MOVIMIENTO` int NOT NULL,
    `DIA` DATE NOT NULL,
    foreign key (ID_AEROLINEA) references AEROLINEA(ID_AEROLINEA),
    foreign key (ID_AEROPUERTO) references AEROPUERTO(ID_AEROPUERTO),
    foreign key (ID_MOVIMIENTO) references MOVIMIENTOS(ID_MOVIMIENTO)
);

insert into VUELOS (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA)
values	(1,1,1,'2021-05-02'),
		(2,1,1,'2021-05-02'),
		(3,2,2,'2021-05-02'),
		(4,3,2,'2021-05-02'),
		(1,3,2,'2021-05-02'),
		(2,1,1,'2021-05-02'),
		(2,3,1,'2021-05-04'),
		(3,4,1,'2021-05-04'),
		(3,4,1,'2021-05-04');

